INSERT INTO players VALUES (1, 'James', 'Carter');
INSERT INTO players VALUES (2, 'Helen', 'Leary');
INSERT INTO players VALUES (3, 'Linda', 'Douglas');

INSERT INTO quiz VALUES(1, 'Which program copies databases from one server to another?', 'answer_a', 'answer_a', 'Mysqlcopydb', 'Mysqldbflush', 'Mysqlflushdb', 'Mysqldbcopy', 'Mysqlmovedb', 'Mysqldbmove', 'sql', 1);
INSERT INTO quiz VALUES(2, 'Which program copies databases from one server to another?', 'answer_a', 'answer_b', 'Mysqlcopydb', 'Mysqldbflush', 'Mysqlflushdb', 'Mysqldbcopy', 'Mysqlmovedb', 'Mysqldbmove', 'sql', 2);
INSERT INTO quiz VALUES(3, 'Which program copies databases from one server to another?', 'answer_a', 'answer_a', 'Mysqlcopydb', 'Mysqldbflush', 'Mysqlflushdb', 'Mysqldbcopy', 'Mysqlmovedb', 'Mysqldbmove', 'sql', 3);
INSERT INTO quiz VALUES(4, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_a', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 1);
INSERT INTO quiz VALUES(5, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_a', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 1);
INSERT INTO quiz VALUES(6, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_a', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 2);
INSERT INTO quiz VALUES(7, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_b', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 3);
INSERT INTO quiz VALUES(8, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_b', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 3);
INSERT INTO quiz VALUES(9, 'Which query will return values containing strings "apple", "banana" or "orange" in the database?', 'answer_a', 'answer_b', 'SELECT * FROM table WHERE field REGEXP ‘apple|banana|orange’;', 'SELECT * FROM table WHERE field LIKE ‘%apple%’ OR field LIKE ‘%banana%’ OR field LIKE ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘%apple%’ OR field = ‘%banana%’ OR field = ‘%orange%’;', 'SELECT * FROM table WHERE field = ‘?apple?’ OR field = ‘?banana?’ OR field = ‘?orange?’;', null, null, 'sql', 3);


